apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater-reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/$YOUR_GITHUB_USERNAME/$YOUR_REPO_NAME.git
    targetRevision: HEAD
    ref: main
    path: 'kustomize/stakater-reloader'
  destination:
    server: https://kubernetes.default.svc
    namespace: 'stakater-reloader'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true