apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/$YOUR_GITHUB_USERNAME/$YOUR_REPO_NAME.git
    targetRevision: HEAD
    ref: main
    path: 'kustomize/homepage'
  destination:
    server: https://kubernetes.default.svc
    namespace: 'homepage'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
